# Generated by Django 6.0.7 on 2026-07-13 16:21

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[store.models.validate_image_size, store.models.validate_image_format]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[store.models.validate_image_size, store.models.validate_image_format]),
        ),
    ]
